// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynssvkbvlsggsaxratez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inluc3N2a2J2bHNnZ3NheHJhdGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjQwOTQsImV4cCI6MjA2MDIwMDA5NH0.ZcrnewPM7Vgt19FDVAV35Of-mBLnKaLAW4uNr82Yjiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);